language: swift
osx_image: xcode7.2

script:
  - swift build
  - xcodebuild -project Huntaway.xcodeproj -scheme "iOS-Test" -sdk iphonesimulator -destination "platform=iOS Simulator, name=iPhone 6" ONLY_ACTIVE_ARCH=NO
